version: "2"

services:

  postgres:
    image: postgres
    container_name: postgres_test
    env_file: .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    restart: always
    ports:
      - 5432:5432